### ISSUE TITLE
在话题页面有一定几率出现左滑动打开侧边菜单而不是返回主页面

### ISSUE THREAD

**Issue by TakWolf** [klesh/cnodejs-swift#1]
出现这种状况之后，左滑动的动作都是打开侧边菜单。

没有找到规律，感觉上开启了横屏状态之后出现的几率变大了。

看了一下实现，侧边菜单是在根导航controller底部的，我进入话题页面之后在顶部状态栏部分滑动（不碰触content）是可以直接打开侧边菜单的。

**Comment by klesh** [comment]
左滑动是指从左向右滑动吗？如果是指这个动作的话，打开侧边菜单应该是预期的行为。返回是设计在左上角的返回导航按钮。反而是返回主页面这个现象不是预期的行为

**Comment by TakWolf** [comment]
左向右滑动  这个动作不应该是结束当前界面返回上一个界面吗？

当处于话题界面的时候，按左上角的返回按钮，或者左向右滑动预期行为都应该是返回到上一级页面

正常情况下，我在话题页面左向右滑是可以返回到主界面的；在主界面左向右滑打开侧边菜单

不正常的情况是我在话题页面，左向右滑就打开菜单了

**Comment by TakWolf** [comment]
这个现象复现如下：iphone6sp  ios9.2

正常情况初始化，话题页面左滑返回上一级界面

在话题页面的状态下，按home键回到桌面，在返回app的时候，很大几率变成了，左滑动打开菜单

**Comment by klesh** [comment]
明白了，把侧滑关联到 navigationbar 应该是比较科学的设定。
