### ISSUE TITLE
进入话题页面有时候会产生剧烈抖动

### ISSUE THREAD

**Issue by TakWolf** [klesh/cnodejs-swift#2]
感觉是由于item初始化引发了多次界面高度计算导致的

**Comment by klesh** [comment]
谢谢反馈，是否在评论页回退时发生？

**Comment by TakWolf** [comment]
试了一下，没发生。发表成功后，list没有自动滑动到最底部，应该也不会产生计算

设备是 iphone6sp

**Comment by TakWolf** [comment]
问一下，markdown渲染是怎么解决的？
话题内容和list的item部分都是webview吗？

**Comment by TakWolf** [comment]
额外再问个问题，发布在这里的 https://klesh.github.io/ ，用的是企业开发者账户吗

**Comment by klesh** [comment]
滑到底部暂时恐怕不行，用了webview，高度要入屏后才能计算，那个闪屏的bug估计也是由这个问题相关出来的。ios怪得很，要改cell高度必须reloadData,reload有可能导致webView高度变化然后闪屏死循环。很头疼

**Comment by klesh** [comment]
是的，我朋友的帐号

**Comment by TakWolf** [comment]
Android这块有同样的问题。我目前没有找到一个好的方案实现原生控件渲染markdown，现在所有markdown都是转成html之后在webview渲染，包括ListView的item部分也是webview。所有也涉及控件重用和高度计算，也会闪烁。Android上的webview基本上没法干预行为

**Comment by klesh** [comment]
关键是图片，自行渲染也是要加载后才能确定高度。这个也是得异步实现，问题依然存在。安卓高度可以自适应的吧？ios不能自适应也不能动态调节真是太不科学了。

**Comment by klesh** [comment]
item 确实会多次计算高度，原来已有一定的措施防止。这个估计是线程安全引起的，我加了个锁，预计能修复这个问题。

**Comment by klesh** [comment]
机率事件难以重现，极有可能线程安全引起。将加锁修复，若下一版继续出现请反馈。
