### ISSUE TITLE
横竖屏切换的适配问题

### ISSUE THREAD

**Issue by TakWolf** [klesh/cnodejs-swift#3]
比如，横屏状态下启动app，之后改到竖屏，侧滑菜单距离就变成全屏的

个人觉得锁定竖屏就好。

如果横屏的话，之前icon版的cnode在iOS上有一个横屏适配，感觉是很不错的，可以参考一下。新版不清楚为啥搞没了

**Comment by klesh** [comment]
我研究一下这个能否动态调节，若不能再锁定。或者提供选项

**Comment by klesh** [comment]
将修复，采用最短的边长*0.7。
