### ISSUE TITLE
侧边菜单选项的问题

### ISSUE THREAD

**Issue by TakWolf** [klesh/cnodejs-swift#5]
1.首次进入页面，内容初始化为全部，但是侧边菜单第一项被选中，tab是精华。感觉全部应该做为第一个位置。

2.侧滑菜单第二栏中的三个，设置、关于、消息觉得不应该有选中状态。应该只有顶部的5个板块tab有选中状态，并且和主页的content对应

**Comment by klesh** [comment]
谢谢反馈，将修正。
