### ISSUE TITLE
Podfile.lock 最好也加到仓库中

### ISSUE THREAD

**Issue by pupboss** [klesh/cnodejs-swift#7]
不然 `pod install` 之后会有一些莫名其妙的问题

**Comment by klesh** [comment]
好的，这个应该是锁定库的版本吧？

**Comment by pupboss** [comment]
对！不过准确说，不是锁定，只是记录下当前环境的版本，避免了第三方库 API 有变动造成的问题

其实也可以在 Podfile 里面指定一下，只不过这个项目里两个都没有...SwiftDate 一更新到 3，编译就失败了

**Comment by klesh** [comment]
已push,谢谢反馈
